import assert from "node:assert/strict";
import { createHash, createHmac } from "node:crypto";
import { spawn } from "node:child_process";
import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import Database from "better-sqlite3";
import ExcelJS from "exceljs";
import { migrateAccounting } from "../scripts/migrate-accounting.mjs";

const root = path.resolve(import.meta.dirname, "..");
const secret = "hatab-accounting-integration-secret-at-least-32-chars";
const requestKey = "accounting-integration-request-2026";
function cookie(user) {
  const value = Buffer.from(JSON.stringify({ sub: user.id, name: user.name, email: user.email, role: user.role, mustChangePassword: false, sessionVersion: user.sessionVersion, exp: Math.floor(Date.now() / 1000) + 3600 })).toString("base64url");
  return `hatab_admin_session=${value}.${createHmac("sha256", secret).update(value).digest("base64url")}`;
}

test("accounting ledger preserves existing balances, writes atomically, exports and backs up", { timeout: 240_000 }, async () => {
  const temporary = fs.mkdtempSync(path.join(os.tmpdir(), "hatab-accounting-test-"));
  const dbFile = path.join(temporary, "ledger.db");
  const dist = path.join(root, `.next-accounting-test-${process.pid}`);
  const nextEnvPath = path.join(root, "next-env.d.ts");
  const nextEnvBefore = fs.readFileSync(nextEnvPath, "utf8");
  const source = new Database(path.join(root, "dev.db"), { readonly: true, fileMustExist: true });
  await source.backup(dbFile); source.close();
  let server;
  let logs = "";
  try {
    const db = new Database(dbFile);
    assert.equal(migrateAccounting(db).changed, false);
    assert.equal(migrateAccounting(db).changed, false);
    const user = db.prepare("SELECT id, name, email, role, sessionVersion FROM User WHERE role='ADMIN' LIMIT 1").get();
    assert.ok(user);
    db.prepare("UPDATE User SET isActive=1, mustChangePassword=0 WHERE id=?").run(user.id);
    const client = db.prepare("INSERT INTO Client(name,phone,createdAt,updatedAt) VALUES('Finance test client','01000000001',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").run().lastInsertRowid;
    const projectId = Number(db.prepare("INSERT INTO Project(clientId,title,totalPrice,totalCost,amountPaid,createdAt,updatedAt) VALUES(?,'Finance test project',12000,6000,2000,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").run(client).lastInsertRowid);
    const supplier = db.prepare("INSERT INTO Supplier(name,phone,createdAt,updatedAt) VALUES('Finance test supplier','01000000002',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").run().lastInsertRowid;
    const supplierOrderId = Number(db.prepare("INSERT INTO SupplierOrder(supplierId,projectId,totalAmount,amountPaid,createdAt,updatedAt) VALUES(?,?,6000,1000,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").run(supplier, projectId).lastInsertRowid);
    db.close();
    const port = await new Promise((resolve, reject) => { const listener = net.createServer(); listener.on("error", reject); listener.listen(0, "127.0.0.1", () => { const port = listener.address().port; listener.close(() => resolve(port)); }); });
    const base = `http://127.0.0.1:${port}`;
    server = spawn(process.execPath, [path.join(root, "node_modules/next/dist/bin/next"), "dev", "--hostname", "127.0.0.1", "--port", String(port)], { cwd: root, env: { ...process.env, DATABASE_URL: `file:${dbFile.replaceAll("\\", "/")}`, AUTH_SECRET: secret, DATA_BACKUP_DIR: path.join(temporary, "backups"), NEXT_DIST_DIR: path.basename(dist), NEXT_TELEMETRY_DISABLED: "1" }, stdio: ["ignore", "pipe", "pipe"], windowsHide: true });
    const log = (chunk) => { logs = (logs + String(chunk)).slice(-14000); };
    server.stdout.on("data", log); server.stderr.on("data", log);
    const deadline = Date.now() + 90_000;
    let ready = false;
    while (Date.now() < deadline) {
      if (server.exitCode !== null) throw new Error(logs);
      try { if ((await fetch(`${base}/api/accounting`, { signal: AbortSignal.timeout(2500) })).status === 401) { ready = true; break; } } catch { /* compile */ }
      await new Promise((resolve) => setTimeout(resolve, 500));
    }
    assert.ok(ready, logs);
    const api = async (method = "GET", body, pathname = "/api/accounting", auth = cookie(user)) => fetch(base + pathname, { method, headers: { cookie: auth, "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined, signal: AbortSignal.timeout(60000) });
    const read = async (response, status) => { const data = await response.json(); assert.equal(response.status, status, JSON.stringify(data)); return data; };
    const snapshot = async () => read(await api(), 200);
    const input = { kind: "RECEIPT", amount: "1200.50", method: "CASH", date: "2026-09-13", projectId, description: "تحصيل", requestKey };
    const first = await read(await api("POST", input), 201);
    await read(await api("POST", input), 200);
    let state = await snapshot();
    assert.equal(state.projects.find((row) => row.id === projectId).amountPaid, 3200.5);
    assert.equal(state.rows.filter((row) => row.key === first.key).length, 1);
    let receipt = state.rows.find((row) => row.key === first.key);
    await read(await api("PATCH", { ...receipt, amount: 1500 }), 200);
    await read(await api("PATCH", { ...receipt, amount: 1800 }), 409);
    await read(await api("POST", { ...input, amount: "6k", requestKey: requestKey + "bad" }), 400);
    await read(await api("POST", { ...input, amount: 4500 }), 409);
    state = await snapshot();
    assert.equal(state.projects.find((row) => row.id === projectId).amountPaid, 3500);
    const outgoing = { kind: "SUPPLIER_PAYMENT", amount: 2000, method: "BANK_TRANSFER", date: "2026-09-13", supplierOrderId, description: "دفعة تصنيع", requestKey: requestKey + "supplier" };
    const created = await read(await api("POST", outgoing), 201);
    state = await snapshot();
    assert.equal(state.supplierOrders.find((row) => row.id === supplierOrderId).amountPaid, 3000);
    let movement = state.rows.find((row) => row.key === created.key);
    await read(await api("PATCH", { ...movement, amount: 2500 }), 200);
    state = await snapshot();
    assert.equal(state.supplierOrders.find((row) => row.id === supplierOrderId).amountPaid, 3500);
    movement = state.rows.find((row) => row.key === created.key);
    await read(await api("PATCH", { operation: "VOID", key: movement.key, token: movement.token, reason: "تمت مراجعة الدفعة وإلغاؤها" }), 200);
    state = await snapshot();
    assert.equal(state.supplierOrders.find((row) => row.id === supplierOrderId).amountPaid, 1000);
    assert.equal(state.rows.find((row) => row.key === created.key).status, "VOID");
    const expense = await read(await api("POST", { ...outgoing, kind: "EXPENSE", supplierOrderId: null, amount: 300, description: "=not a formula", requestKey: requestKey + "expense" }), 201);
    const exportResponse = await api("GET", null, "/api/accounting?format=xlsx");
    assert.equal(exportResponse.status, 200);
    const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(Buffer.from(await exportResponse.arrayBuffer()));
    assert.equal(workbook.worksheets.length, 4);
    const sheet = workbook.getWorksheet("الحركات");
    let exported;
    sheet.eachRow((row) => { if (row.getCell(1).value === expense.key) exported = row.getCell(7).value; });
    assert.equal(typeof exported, "string"); assert.notEqual(exported, "=not a formula");
    const operations = await api("POST", { scope: "OPERATIONS" }, "/api/data-management/backup");
    assert.equal(operations.status, 200, await operations.clone().text());
    const backup = await operations.json();
    assert.ok(backup.records.finance_entries.some((row) => row.description === "=not a formula"));

    const upload = async (pathname, file, dryRun = false) => {
      const form = new FormData(); form.set("file", file); form.set("dryRun", String(dryRun));
      return fetch(base + pathname, { method: "POST", headers: { cookie: cookie(user) }, body: form, signal: AbortSignal.timeout(60000) });
    };
    const financeExport = await api("GET", null, "/api/data-management/export?modules=finance_entries");
    assert.equal(financeExport.status, 200);
    const financeWorkbook = new ExcelJS.Workbook(); await financeWorkbook.xlsx.load(Buffer.from(await financeExport.arrayBuffer()));
    const financeSheet = financeWorkbook.getWorksheet("finance_entries");
    const financeHeaders = new Map(); financeSheet.getRow(1).eachCell((cell, column) => financeHeaders.set(String(cell.value), column));
    financeSheet.eachRow((row, index) => { if (index > 1 && row.getCell(financeHeaders.get("external_key")).value === `ACCOUNTING-${requestKey}expense`) row.getCell(financeHeaders.get("amount")).value = 350; });
    await read(await upload("/api/data-management/import", new File([Buffer.from(await financeWorkbook.xlsx.writeBuffer())], "finance.xlsx")), 200);
    state = await snapshot();
    assert.equal(state.rows.find((row) => row.key === expense.key).amount, 350);
    assert.equal(state.supplierOrders.find((row) => row.id === supplierOrderId).amountPaid, 1000);
    await read(await api("POST", { ...outgoing, amount: 500, requestKey: requestKey + "supplier-new" }), 201);
    const pairExport = await api("GET", null, "/api/data-management/export?modules=supplier_orders,finance_entries");
    assert.equal(pairExport.status, 200);
    await read(await upload("/api/data-management/import", new File([await pairExport.arrayBuffer()], "supplier-finance.xlsx")), 200);
    state = await snapshot();
    assert.equal(state.supplierOrders.find((row) => row.id === supplierOrderId).amountPaid, 1500, "importing balance and ledger together must not double count");
    const freshResponse = await api("POST", { scope: "OPERATIONS" }, "/api/data-management/backup");
    assert.equal(freshResponse.status, 200); const freshBackup = await freshResponse.text();
    await read(await upload("/api/data-management/restore", new File([freshBackup], "finance-backup.json"), true), 200);
    await read(await upload("/api/data-management/restore", new File([freshBackup], "finance-backup.json")), 200);
    await read(await api("POST", { ...input, amount: 200, requestKey: requestKey + "receipt-newer" }), 201);
    const refusedReceiptRestore = await read(await upload("/api/data-management/restore", new File([freshBackup], "older-receipts.json")), 422);
    assert.ok(refusedReceiptRestore.issues.some((entry) => entry.code === "RECEIPT_RESTORE_REQUIRES_COMPLETE_LEDGER"));
    state = await snapshot();
    assert.equal(state.projects.find((row) => row.id === projectId).amountPaid, 3700, "refused restore must not mutate the customer's balance");
    await read(await api("POST", { ...outgoing, amount: 250, requestKey: requestKey + "supplier-newer" }), 201);
    const refusedRestore = await read(await upload("/api/data-management/restore", new File([freshBackup], "older-finance.json")), 422);
    assert.ok(refusedRestore.issues.some((entry) => entry.code === "FINANCE_RESTORE_REQUIRES_COMPLETE_LEDGER"));
    const legacy = JSON.parse(freshBackup);
    for (const section of ["records", "data", "bindings", "counts"]) delete legacy[section].finance_entries;
    const canonical = (value) => Array.isArray(value) ? value.map(canonical) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, canonical(item)])) : value;
    delete legacy.sourceHash;
    legacy.sourceHash = createHash("sha256").update(JSON.stringify(canonical(legacy))).digest("hex");
    const refusedLegacy = await read(await upload("/api/data-management/restore", new File([JSON.stringify(legacy)], "pre-accounting.json")), 422);
    assert.ok(refusedLegacy.issues.some((entry) => entry.code === "BACKUP_PREDATES_ACCOUNTING"));
    const projectPayments = await api("GET", null, "/api/data-management/export?modules=projects,payments");
    assert.equal(projectPayments.status, 200);
    await read(await upload("/api/data-management/import", new File([await projectPayments.arrayBuffer()], "project-payments.xlsx")), 200);
    state = await snapshot();
    assert.equal(state.projects.find((row) => row.id === projectId).amountPaid, 3700, "combined snapshot preserves the declared total without dropping opening balances");
    const paymentExport = await api("GET", null, "/api/data-management/export?modules=payments");
    assert.equal(paymentExport.status, 200);
    const paymentWorkbook = new ExcelJS.Workbook(); await paymentWorkbook.xlsx.load(Buffer.from(await paymentExport.arrayBuffer()));
    const paymentSheet = paymentWorkbook.getWorksheet("payments");
    const paymentHeaders = new Map(); paymentSheet.getRow(1).eachCell((cell, column) => paymentHeaders.set(String(cell.value), column));
    paymentSheet.eachRow((row, index) => { if (index > 1 && row.getCell(paymentHeaders.get("external_key")).value === `ACCOUNTING-${requestKey}`) row.getCell(paymentHeaders.get("amount")).value = 1600; });
    await read(await upload("/api/data-management/import", new File([Buffer.from(await paymentWorkbook.xlsx.writeBuffer())], "payments-update.xlsx")), 200);
    state = await snapshot();
    assert.equal(state.projects.find((row) => row.id === projectId).amountPaid, 3800, "receipt-only import adjusts the receipt while preserving the 2000 opening balance");
    const legacyReceipt = { amount: "500.00", method: "CASH", date: "2026-09-13T00:00:00.000Z", notes: "Project detail form receipt", requestKey: requestKey + "legacy-route" };
    const legacyPath = `/api/projects/${projectId}/payments`;
    const legacyCreated = await read(await api("POST", legacyReceipt, legacyPath), 201);
    assert.equal(legacyCreated.amountPaid, 4300);
    assert.equal(legacyCreated.payment.amount, 500);
    assert.equal(legacyCreated.remaining, 7700);
    const legacyRepeated = await read(await api("POST", legacyReceipt, legacyPath), 200);
    assert.equal(legacyRepeated.duplicate, true);
    assert.equal(legacyRepeated.payment.id, legacyCreated.payment.id);
    const legacyList = await read(await api("GET", null, legacyPath), 200);
    assert.equal(legacyList.totalPaid, 4300);
    assert.equal(legacyList.openingBalance, 2000);
    await read(await api("POST", { ...legacyReceipt, amount: "300trailing", requestKey: requestKey + "invalid-legacy" }, legacyPath), 400);
    await read(await api("POST", legacyReceipt, `/api/projects/${projectId}trailing/payments`), 400);
    state = await snapshot();
    assert.equal(state.projects.find((row) => row.id === projectId).amountPaid, 4300, "legacy form retries and invalid values must not duplicate or truncate receipts");
    const readonly = new Database(dbFile, { readonly: true });
    assert.ok(readonly.prepare("SELECT count(*) AS count FROM DataChangeAudit WHERE module='finance_entries'").get().count >= 4);
    assert.equal(readonly.pragma("integrity_check", { simple: true }), "ok");
    assert.equal(readonly.prepare("PRAGMA foreign_key_check").all().length, 0);
    readonly.close();
  } finally {
    if (server && server.exitCode === null) { server.kill("SIGTERM"); await new Promise((resolve) => { const timer = setTimeout(resolve, 5000); server.once("exit", () => { clearTimeout(timer); resolve(); }); }); }
    if (fs.readFileSync(nextEnvPath, "utf8").includes(path.basename(dist))) fs.writeFileSync(nextEnvPath, nextEnvBefore);
    for (const [directory, parent, prefix] of [[temporary, os.tmpdir(), "hatab-accounting-test-"], [dist, root, ".next-accounting-test-"]]) {
      const resolved = path.resolve(directory);
      if (path.dirname(resolved) !== path.resolve(parent) || !path.basename(resolved).startsWith(prefix)) throw new Error("Unsafe test cleanup target");
      fs.rmSync(resolved, { recursive: true, force: true, maxRetries: 8, retryDelay: 500 });
    }
  }
});
